[project]
name = "qi-compute-api-client"
version = "0.54.1"
description = "An API client for the Compute Job Manager of Quantum Inspire."
authors = [{ name = "Quantum Inspire", email = "support@quantum-inspire.eu" }]
requires-python = ">=3.9,<3.13"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "aiohttp==3.13.1",
    "pydantic==2.12.3",
    "python-dateutil==2.9.0.post0",
    "urllib3==2.5.0",
    "requests==2.32.5",
    "typing-extensions==4.15.0",
    "aiohttp-retry==2.9.1",
]

[project.urls]
Repository = "https://github.com/QuTech-Delft/compute-api-client"

[dependency-groups]
dev = [
    "pytest==8.4.2",
    "coverage[toml]>=7.6.10,<8",
    "pytest-cov==7.0.0",
    "mypy==1.18.2",
    "docformatter==1.7.7",
    "pytest-mock==3.15.1",
    "black==25.9.0",
    "pytest-asyncio==1.2.0",
    "ruff==0.14.2",
    "deptry==0.23.1",
    "types-requests==2.32.4.20250913",
    "responses==0.25.8",
    "refurb==2.2.0 ; python_version >= '3.10'",
]

[tool.hatch.build.targets.sdist]
include = ["compute_api_client", "qi2_shared"]
exclude = ["compute_api_client/test", "tests"]

[tool.hatch.build.targets.wheel]
include = ["compute_api_client", "qi2_shared"]
exclude = ["compute_api_client/test", "tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "-v --cov --cov-report term-missing:skip-covered --cov-report xml --junitxml=report.xml"
asyncio_mode = "auto"
testpaths = "tests/*"

[tool.coverage.run]
branch = true
source = ["qi2_shared"]
omit = ["compute_api_client/*"]

[tool.mypy]
exclude = ["compute_api_client/*"]

[tool.deptry]
exclude = ["compute_api_client/*", "tests/*", ".venv/*"]

[tool.deptry.per_rule_ignores]
DEP002 = ["aiohttp", "python-dateutil", "urllib3", "aiohttp-retry"]

[tool.ruff]
exclude = ["compute_api_client/*"]
