# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from compute_api_client.configuration import Configuration


class AlgorithmCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_id': 'int',
        'type': 'AlgorithmType',
        'shared': 'ShareType',
        'link': 'str'
    }

    attribute_map = {
        'project_id': 'project_id',
        'type': 'type',
        'shared': 'shared',
        'link': 'link'
    }

    def __init__(self, project_id=None, type=None, shared=None, link=None, local_vars_configuration=None):  # noqa: E501
        """AlgorithmCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._project_id = None
        self._type = None
        self._shared = None
        self._link = None
        self.discriminator = None

        self.project_id = project_id
        self.type = type
        self.shared = shared
        self.link = link

    @property
    def project_id(self):
        """Gets the project_id of this AlgorithmCreate.  # noqa: E501


        :return: The project_id of this AlgorithmCreate.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this AlgorithmCreate.


        :param project_id: The project_id of this AlgorithmCreate.  # noqa: E501
        :type project_id: int
        """
        if self.local_vars_configuration.client_side_validation and project_id is None:  # noqa: E501
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def type(self):
        """Gets the type of this AlgorithmCreate.  # noqa: E501


        :return: The type of this AlgorithmCreate.  # noqa: E501
        :rtype: AlgorithmType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AlgorithmCreate.


        :param type: The type of this AlgorithmCreate.  # noqa: E501
        :type type: AlgorithmType
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def shared(self):
        """Gets the shared of this AlgorithmCreate.  # noqa: E501


        :return: The shared of this AlgorithmCreate.  # noqa: E501
        :rtype: ShareType
        """
        return self._shared

    @shared.setter
    def shared(self, shared):
        """Sets the shared of this AlgorithmCreate.


        :param shared: The shared of this AlgorithmCreate.  # noqa: E501
        :type shared: ShareType
        """
        if self.local_vars_configuration.client_side_validation and shared is None:  # noqa: E501
            raise ValueError("Invalid value for `shared`, must not be `None`")  # noqa: E501

        self._shared = shared

    @property
    def link(self):
        """Gets the link of this AlgorithmCreate.  # noqa: E501


        :return: The link of this AlgorithmCreate.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this AlgorithmCreate.


        :param link: The link of this AlgorithmCreate.  # noqa: E501
        :type link: str
        """

        self._link = link

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlgorithmCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AlgorithmCreate):
            return True

        return self.to_dict() != other.to_dict()
