# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from compute_api_client.configuration import Configuration


class BackendPatch(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'status': 'BackendStatus',
        'last_heartbeat': 'datetime'
    }

    attribute_map = {
        'status': 'status',
        'last_heartbeat': 'last_heartbeat'
    }

    def __init__(self, status=None, last_heartbeat=None, local_vars_configuration=None):  # noqa: E501
        """BackendPatch - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._status = None
        self._last_heartbeat = None
        self.discriminator = None

        self.status = status
        self.last_heartbeat = last_heartbeat

    @property
    def status(self):
        """Gets the status of this BackendPatch.  # noqa: E501


        :return: The status of this BackendPatch.  # noqa: E501
        :rtype: BackendStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BackendPatch.


        :param status: The status of this BackendPatch.  # noqa: E501
        :type status: BackendStatus
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def last_heartbeat(self):
        """Gets the last_heartbeat of this BackendPatch.  # noqa: E501


        :return: The last_heartbeat of this BackendPatch.  # noqa: E501
        :rtype: datetime
        """
        return self._last_heartbeat

    @last_heartbeat.setter
    def last_heartbeat(self, last_heartbeat):
        """Sets the last_heartbeat of this BackendPatch.


        :param last_heartbeat: The last_heartbeat of this BackendPatch.  # noqa: E501
        :type last_heartbeat: datetime
        """
        if self.local_vars_configuration.client_side_validation and last_heartbeat is None:  # noqa: E501
            raise ValueError("Invalid value for `last_heartbeat`, must not be `None`")  # noqa: E501

        self._last_heartbeat = last_heartbeat

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackendPatch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BackendPatch):
            return True

        return self.to_dict() != other.to_dict()
