# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from compute_api_client.configuration import Configuration


class BatchRunCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'run_ids': 'list[int]',
        'queued_at': 'datetime',
        'finished_at': 'datetime',
        'runtime_type_id': 'int',
        'runtime_id': 'int'
    }

    attribute_map = {
        'run_ids': 'run_ids',
        'queued_at': 'queued_at',
        'finished_at': 'finished_at',
        'runtime_type_id': 'runtime_type_id',
        'runtime_id': 'runtime_id'
    }

    def __init__(self, run_ids=None, queued_at=None, finished_at=None, runtime_type_id=None, runtime_id=None, local_vars_configuration=None):  # noqa: E501
        """BatchRunCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._run_ids = None
        self._queued_at = None
        self._finished_at = None
        self._runtime_type_id = None
        self._runtime_id = None
        self.discriminator = None

        self.run_ids = run_ids
        self.queued_at = queued_at
        self.finished_at = finished_at
        self.runtime_type_id = runtime_type_id
        self.runtime_id = runtime_id

    @property
    def run_ids(self):
        """Gets the run_ids of this BatchRunCreate.  # noqa: E501


        :return: The run_ids of this BatchRunCreate.  # noqa: E501
        :rtype: list[int]
        """
        return self._run_ids

    @run_ids.setter
    def run_ids(self, run_ids):
        """Sets the run_ids of this BatchRunCreate.


        :param run_ids: The run_ids of this BatchRunCreate.  # noqa: E501
        :type run_ids: list[int]
        """
        if self.local_vars_configuration.client_side_validation and run_ids is None:  # noqa: E501
            raise ValueError("Invalid value for `run_ids`, must not be `None`")  # noqa: E501

        self._run_ids = run_ids

    @property
    def queued_at(self):
        """Gets the queued_at of this BatchRunCreate.  # noqa: E501


        :return: The queued_at of this BatchRunCreate.  # noqa: E501
        :rtype: datetime
        """
        return self._queued_at

    @queued_at.setter
    def queued_at(self, queued_at):
        """Sets the queued_at of this BatchRunCreate.


        :param queued_at: The queued_at of this BatchRunCreate.  # noqa: E501
        :type queued_at: datetime
        """
        if self.local_vars_configuration.client_side_validation and queued_at is None:  # noqa: E501
            raise ValueError("Invalid value for `queued_at`, must not be `None`")  # noqa: E501

        self._queued_at = queued_at

    @property
    def finished_at(self):
        """Gets the finished_at of this BatchRunCreate.  # noqa: E501


        :return: The finished_at of this BatchRunCreate.  # noqa: E501
        :rtype: datetime
        """
        return self._finished_at

    @finished_at.setter
    def finished_at(self, finished_at):
        """Sets the finished_at of this BatchRunCreate.


        :param finished_at: The finished_at of this BatchRunCreate.  # noqa: E501
        :type finished_at: datetime
        """

        self._finished_at = finished_at

    @property
    def runtime_type_id(self):
        """Gets the runtime_type_id of this BatchRunCreate.  # noqa: E501


        :return: The runtime_type_id of this BatchRunCreate.  # noqa: E501
        :rtype: int
        """
        return self._runtime_type_id

    @runtime_type_id.setter
    def runtime_type_id(self, runtime_type_id):
        """Sets the runtime_type_id of this BatchRunCreate.


        :param runtime_type_id: The runtime_type_id of this BatchRunCreate.  # noqa: E501
        :type runtime_type_id: int
        """
        if self.local_vars_configuration.client_side_validation and runtime_type_id is None:  # noqa: E501
            raise ValueError("Invalid value for `runtime_type_id`, must not be `None`")  # noqa: E501

        self._runtime_type_id = runtime_type_id

    @property
    def runtime_id(self):
        """Gets the runtime_id of this BatchRunCreate.  # noqa: E501


        :return: The runtime_id of this BatchRunCreate.  # noqa: E501
        :rtype: int
        """
        return self._runtime_id

    @runtime_id.setter
    def runtime_id(self, runtime_id):
        """Sets the runtime_id of this BatchRunCreate.


        :param runtime_id: The runtime_id of this BatchRunCreate.  # noqa: E501
        :type runtime_id: int
        """

        self._runtime_id = runtime_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchRunCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BatchRunCreate):
            return True

        return self.to_dict() != other.to_dict()
