# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from compute_api_client.configuration import Configuration


class MetadataCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'runtime_id': 'int',
        'created_on': 'datetime',
        'data': 'object'
    }

    attribute_map = {
        'runtime_id': 'runtime_id',
        'created_on': 'created_on',
        'data': 'data'
    }

    def __init__(self, runtime_id=None, created_on=None, data=None, local_vars_configuration=None):  # noqa: E501
        """MetadataCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._runtime_id = None
        self._created_on = None
        self._data = None
        self.discriminator = None

        self.runtime_id = runtime_id
        self.created_on = created_on
        self.data = data

    @property
    def runtime_id(self):
        """Gets the runtime_id of this MetadataCreate.  # noqa: E501


        :return: The runtime_id of this MetadataCreate.  # noqa: E501
        :rtype: int
        """
        return self._runtime_id

    @runtime_id.setter
    def runtime_id(self, runtime_id):
        """Sets the runtime_id of this MetadataCreate.


        :param runtime_id: The runtime_id of this MetadataCreate.  # noqa: E501
        :type runtime_id: int
        """
        if self.local_vars_configuration.client_side_validation and runtime_id is None:  # noqa: E501
            raise ValueError("Invalid value for `runtime_id`, must not be `None`")  # noqa: E501

        self._runtime_id = runtime_id

    @property
    def created_on(self):
        """Gets the created_on of this MetadataCreate.  # noqa: E501


        :return: The created_on of this MetadataCreate.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this MetadataCreate.


        :param created_on: The created_on of this MetadataCreate.  # noqa: E501
        :type created_on: datetime
        """
        if self.local_vars_configuration.client_side_validation and created_on is None:  # noqa: E501
            raise ValueError("Invalid value for `created_on`, must not be `None`")  # noqa: E501

        self._created_on = created_on

    @property
    def data(self):
        """Gets the data of this MetadataCreate.  # noqa: E501


        :return: The data of this MetadataCreate.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this MetadataCreate.


        :param data: The data of this MetadataCreate.  # noqa: E501
        :type data: object
        """
        if self.local_vars_configuration.client_side_validation and data is None:  # noqa: E501
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MetadataCreate):
            return True

        return self.to_dict() != other.to_dict()
