# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from compute_api_client.configuration import Configuration


class Team(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'slug': 'str',
        'permission_group_ids': 'list[int]',
        'permission_ids': 'list[int]',
        'individual_user': 'bool',
        'id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'slug': 'slug',
        'permission_group_ids': 'permission_group_ids',
        'permission_ids': 'permission_ids',
        'individual_user': 'individual_user',
        'id': 'id'
    }

    def __init__(self, name=None, slug=None, permission_group_ids=None, permission_ids=None, individual_user=None, id=None, local_vars_configuration=None):  # noqa: E501
        """Team - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._slug = None
        self._permission_group_ids = None
        self._permission_ids = None
        self._individual_user = None
        self._id = None
        self.discriminator = None

        self.name = name
        self.slug = slug
        self.permission_group_ids = permission_group_ids
        self.permission_ids = permission_ids
        self.individual_user = individual_user
        self.id = id

    @property
    def name(self):
        """Gets the name of this Team.  # noqa: E501


        :return: The name of this Team.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Team.


        :param name: The name of this Team.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this Team.  # noqa: E501


        :return: The slug of this Team.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this Team.


        :param slug: The slug of this Team.  # noqa: E501
        :type slug: str
        """
        if self.local_vars_configuration.client_side_validation and slug is None:  # noqa: E501
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501

        self._slug = slug

    @property
    def permission_group_ids(self):
        """Gets the permission_group_ids of this Team.  # noqa: E501


        :return: The permission_group_ids of this Team.  # noqa: E501
        :rtype: list[int]
        """
        return self._permission_group_ids

    @permission_group_ids.setter
    def permission_group_ids(self, permission_group_ids):
        """Sets the permission_group_ids of this Team.


        :param permission_group_ids: The permission_group_ids of this Team.  # noqa: E501
        :type permission_group_ids: list[int]
        """
        if self.local_vars_configuration.client_side_validation and permission_group_ids is None:  # noqa: E501
            raise ValueError("Invalid value for `permission_group_ids`, must not be `None`")  # noqa: E501

        self._permission_group_ids = permission_group_ids

    @property
    def permission_ids(self):
        """Gets the permission_ids of this Team.  # noqa: E501


        :return: The permission_ids of this Team.  # noqa: E501
        :rtype: list[int]
        """
        return self._permission_ids

    @permission_ids.setter
    def permission_ids(self, permission_ids):
        """Sets the permission_ids of this Team.


        :param permission_ids: The permission_ids of this Team.  # noqa: E501
        :type permission_ids: list[int]
        """
        if self.local_vars_configuration.client_side_validation and permission_ids is None:  # noqa: E501
            raise ValueError("Invalid value for `permission_ids`, must not be `None`")  # noqa: E501

        self._permission_ids = permission_ids

    @property
    def individual_user(self):
        """Gets the individual_user of this Team.  # noqa: E501


        :return: The individual_user of this Team.  # noqa: E501
        :rtype: bool
        """
        return self._individual_user

    @individual_user.setter
    def individual_user(self, individual_user):
        """Sets the individual_user of this Team.


        :param individual_user: The individual_user of this Team.  # noqa: E501
        :type individual_user: bool
        """
        if self.local_vars_configuration.client_side_validation and individual_user is None:  # noqa: E501
            raise ValueError("Invalid value for `individual_user`, must not be `None`")  # noqa: E501

        self._individual_user = individual_user

    @property
    def id(self):
        """Gets the id of this Team.  # noqa: E501


        :return: The id of this Team.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Team.


        :param id: The id of this Team.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Team):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Team):
            return True

        return self.to_dict() != other.to_dict()
