# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.users_api import UsersApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_users_post(self):
        """Test case for create_user_users_post

        Create user  # noqa: E501
        """
        pass

    def test_delete_user_users_id_delete(self):
        """Test case for delete_user_users_id_delete

        Destroy user  # noqa: E501
        """
        pass

    def test_read_user_users_id_get(self):
        """Test case for read_user_users_id_get

        Retrieve user  # noqa: E501
        """
        pass

    def test_read_users_users_get(self):
        """Test case for read_users_users_get

        List users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
