# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import compute_api_client
from compute_api_client.models.commit_in import CommitIn  # noqa: E501
from compute_api_client.rest import ApiException

class TestCommitIn(unittest.TestCase):
    """CommitIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CommitIn
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = compute_api_client.models.commit_in.CommitIn()  # noqa: E501
        if include_optional :
            return CommitIn(
                hash = '', 
                description = '', 
                algorithm_id = 1.0
            )
        else :
            return CommitIn(
                hash = '',
                description = '',
                algorithm_id = 1.0,
        )

    def testCommitIn(self):
        """Test CommitIn"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
