# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.projects_api import ProjectsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project_projects_post(self):
        """Test case for create_project_projects_post

        Create project  # noqa: E501
        """
        pass

    def test_delete_project_projects_id_delete(self):
        """Test case for delete_project_projects_id_delete

        Destroy project  # noqa: E501
        """
        pass

    def test_partial_update_project_projects_id_patch(self):
        """Test case for partial_update_project_projects_id_patch

        Partially update project  # noqa: E501
        """
        pass

    def test_read_project_projects_id_get(self):
        """Test case for read_project_projects_id_get

        Retrieve project  # noqa: E501
        """
        pass

    def test_read_projects_projects_get(self):
        """Test case for read_projects_projects_get

        List projects  # noqa: E501
        """
        pass

    def test_update_project_projects_id_put(self):
        """Test case for update_project_projects_id_put

        Update project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
