# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.runs_api import RunsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestRunsApi(unittest.TestCase):
    """RunsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.runs_api.RunsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_run_runs_post(self):
        """Test case for create_run_runs_post

        Create run  # noqa: E501
        """
        pass

    def test_delete_run_runs_id_delete(self):
        """Test case for delete_run_runs_id_delete

        Destroy run  # noqa: E501
        """
        pass

    def test_read_run_runs_id_get(self):
        """Test case for read_run_runs_id_get

        Retrieve run  # noqa: E501
        """
        pass

    def test_read_runs_runs_get(self):
        """Test case for read_runs_runs_get

        List runs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
