# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.metadata_api import MetadataApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.metadata_api.MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_metadata_metadata_post(self):
        """Test case for create_metadata_metadata_post

        Create metadata  # noqa: E501
        """
        pass

    def test_read_metadata_by_runtime_id_metadata_runtime_runtime_id_get(self):
        """Test case for read_metadata_by_runtime_id_metadata_runtime_runtime_id_get

        Retrieve metadata by runtime ID  # noqa: E501
        """
        pass

    def test_read_metadata_metadata_id_get(self):
        """Test case for read_metadata_metadata_id_get

        Get metadata by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
