# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.backend_type import BackendType

class TestBackendType(unittest.TestCase):
    """BackendType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendType:
        """Test BackendType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendType`
        """
        model = BackendType()
        if include_optional:
            return BackendType(
                id = 56,
                name = '',
                infrastructure = '',
                description = '',
                image_id = '',
                is_hardware = True,
                features = [
                    ''
                    ],
                default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(),
                native_gateset = compute_api_client.models.native_gateset.Native Gateset()
            )
        else:
            return BackendType(
                id = 56,
                name = '',
                infrastructure = '',
                description = '',
                image_id = '',
                is_hardware = True,
                features = [
                    ''
                    ],
                default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(),
                native_gateset = compute_api_client.models.native_gateset.Native Gateset(),
        )
        """

    def testBackendType(self):
        """Test BackendType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
