# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.page_member import PageMember

class TestPageMember(unittest.TestCase):
    """PageMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageMember:
        """Test PageMember
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageMember`
        """
        model = PageMember()
        if include_optional:
            return PageMember(
                items = [
                    compute_api_client.models.member.Member(
                        id = 56, 
                        team_id = 56, 
                        user_id = 56, 
                        role = 'member', 
                        is_active = True, )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageMember(
                items = [
                    compute_api_client.models.member.Member(
                        id = 56, 
                        team_id = 56, 
                        user_id = 56, 
                        role = 'member', 
                        is_active = True, )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageMember(self):
        """Test PageMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
