# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_create_job_jobs_post(self) -> None:
        """Test case for create_job_jobs_post

        Create job
        """
        pass

    def test_delete_job_jobs_id_delete(self) -> None:
        """Test case for delete_job_jobs_id_delete

        Destroy job
        """
        pass

    def test_read_job_jobs_id_get(self) -> None:
        """Test case for read_job_jobs_id_get

        Retrieve job
        """
        pass

    def test_read_jobs_jobs_get(self) -> None:
        """Test case for read_jobs_jobs_get

        List jobs
        """
        pass

    def test_update_job_status_jobs_id_patch(self) -> None:
        """Test case for update_job_status_jobs_id_patch

        Update Job Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
