# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.page_backend_type import PageBackendType

class TestPageBackendType(unittest.TestCase):
    """PageBackendType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageBackendType:
        """Test PageBackendType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageBackendType`
        """
        model = PageBackendType()
        if include_optional:
            return PageBackendType(
                items = [
                    compute_api_client.models.backend_type.BackendType(
                        id = 56, 
                        name = '', 
                        infrastructure = '', 
                        description = '', 
                        image_id = '', 
                        is_hardware = True, 
                        features = [
                            ''
                            ], 
                        default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(), 
                        native_gateset = compute_api_client.models.native_gateset.Native Gateset(), 
                        status = 'offline', 
                        default_number_of_shots = 56, 
                        max_number_of_shots = 56, )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageBackendType(
                items = [
                    compute_api_client.models.backend_type.BackendType(
                        id = 56, 
                        name = '', 
                        infrastructure = '', 
                        description = '', 
                        image_id = '', 
                        is_hardware = True, 
                        features = [
                            ''
                            ], 
                        default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(), 
                        native_gateset = compute_api_client.models.native_gateset.Native Gateset(), 
                        status = 'offline', 
                        default_number_of_shots = 56, 
                        max_number_of_shots = 56, )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageBackendType(self):
        """Test PageBackendType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
