# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_read_transaction_transactions_id_get(self) -> None:
        """Test case for read_transaction_transactions_id_get

        Retrieve transactions
        """
        pass

    def test_read_transactions_transactions_get(self) -> None:
        """Test case for read_transactions_transactions_get

        List transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
