# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.page_algorithm import PageAlgorithm

class TestPageAlgorithm(unittest.TestCase):
    """PageAlgorithm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageAlgorithm:
        """Test PageAlgorithm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageAlgorithm`
        """
        model = PageAlgorithm()
        if include_optional:
            return PageAlgorithm(
                items = [
                    compute_api_client.models.algorithm.Algorithm(
                        id = 56, 
                        project_id = 56, 
                        type = 'hybrid', 
                        shared = 'private', 
                        link = '', 
                        name = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageAlgorithm(
                items = [
                    compute_api_client.models.algorithm.Algorithm(
                        id = 56, 
                        project_id = 56, 
                        type = 'hybrid', 
                        shared = 'private', 
                        link = '', 
                        name = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageAlgorithm(self):
        """Test PageAlgorithm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
