# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.batch_jobs_api import BatchJobsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestBatchJobsApi(unittest.TestCase):
    """BatchJobsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.batch_jobs_api.BatchJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_batch_job_batch_jobs_post(self):
        """Test case for create_batch_job_batch_jobs_post

        Create batch job  # noqa: E501
        """
        pass

    def test_enqueue_batch_job_batch_jobs_id_enqueue_patch(self):
        """Test case for enqueue_batch_job_batch_jobs_id_enqueue_patch

        Enqueue batch job for execution  # noqa: E501
        """
        pass

    def test_finish_batch_job_batch_jobs_id_finish_patch(self):
        """Test case for finish_batch_job_batch_jobs_id_finish_patch

        Finish batch job  # noqa: E501
        """
        pass

    def test_peek_batch_job_batch_jobs_peek_patch(self):
        """Test case for peek_batch_job_batch_jobs_peek_patch

        Peek batch job  # noqa: E501
        """
        pass

    def test_pop_batch_job_batch_jobs_pop_patch(self):
        """Test case for pop_batch_job_batch_jobs_pop_patch

        Take batch job  # noqa: E501
        """
        pass

    def test_read_batch_jobs_batch_jobs_get(self):
        """Test case for read_batch_jobs_batch_jobs_get

        List batch jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
