# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.backend_api import BackendApi


class TestBackendApi(unittest.TestCase):
    """BackendApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackendApi()

    def tearDown(self) -> None:
        pass

    def test_create_backend_backends_post(self) -> None:
        """Test case for create_backend_backends_post

        Create backend
        """
        pass

    def test_read_backend_backends_id_get(self) -> None:
        """Test case for read_backend_backends_id_get

        Retrieve backend
        """
        pass

    def test_read_backend_self_backends_me_get(self) -> None:
        """Test case for read_backend_self_backends_me_get

        Retrieve backend
        """
        pass

    def test_read_backends_backends_get(self) -> None:
        """Test case for read_backends_backends_get

        List backends
        """
        pass

    def test_update_backend_self_backends_me_patch(self) -> None:
        """Test case for update_backend_self_backends_me_patch

        Update backend
        """
        pass


if __name__ == '__main__':
    unittest.main()
