# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.algorithm_type import AlgorithmType

class TestAlgorithmType(unittest.TestCase):
    """AlgorithmType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlgorithmType(self):
        """Test AlgorithmType"""
        # inst = AlgorithmType()

if __name__ == '__main__':
    unittest.main()
