# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.permissions_api import PermissionsApi


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermissionsApi()

    def tearDown(self) -> None:
        pass

    def test_read_permission_group_permission_groups_id_get(self) -> None:
        """Test case for read_permission_group_permission_groups_id_get

        Retrieve permission groups
        """
        pass

    def test_read_permission_groups_permission_groups_get(self) -> None:
        """Test case for read_permission_groups_permission_groups_get

        List permission groups
        """
        pass

    def test_read_permission_permissions_id_get(self) -> None:
        """Test case for read_permission_permissions_id_get

        Retrieve permissions
        """
        pass

    def test_read_permissions_permissions_get(self) -> None:
        """Test case for read_permissions_permissions_get

        List permissions
        """
        pass


if __name__ == '__main__':
    unittest.main()
