# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.members_api import MembersApi


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()

    def tearDown(self) -> None:
        pass

    def test_create_member_members_post(self) -> None:
        """Test case for create_member_members_post

        Create member
        """
        pass

    def test_delete_member_members_id_delete(self) -> None:
        """Test case for delete_member_members_id_delete

        Destroy member
        """
        pass

    def test_read_member_members_id_get(self) -> None:
        """Test case for read_member_members_id_get

        Retrieve member
        """
        pass

    def test_read_members_members_get(self) -> None:
        """Test case for read_members_members_get

        List members
        """
        pass


if __name__ == '__main__':
    unittest.main()
