# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Create user
        """
        pass

    def test_delete_user_users_id_delete(self) -> None:
        """Test case for delete_user_users_id_delete

        Destroy user
        """
        pass

    def test_read_user_users_id_get(self) -> None:
        """Test case for read_user_users_id_get

        Retrieve user
        """
        pass

    def test_read_users_users_get(self) -> None:
        """Test case for read_users_users_get

        List users
        """
        pass


if __name__ == '__main__':
    unittest.main()
