# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.teams_api import TeamsApi


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamsApi()

    def tearDown(self) -> None:
        pass

    def test_read_team_teams_id_get(self) -> None:
        """Test case for read_team_teams_id_get

        Retrieve teams
        """
        pass

    def test_read_teams_teams_get(self) -> None:
        """Test case for read_teams_teams_get

        List teams
        """
        pass


if __name__ == '__main__':
    unittest.main()
