# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.jobs_api import JobsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_job_jobs_post(self):
        """Test case for create_job_jobs_post

        Create job  # noqa: E501
        """
        pass

    def test_delete_job_jobs_id_delete(self):
        """Test case for delete_job_jobs_id_delete

        Destroy job  # noqa: E501
        """
        pass

    def test_read_job_jobs_id_get(self):
        """Test case for read_job_jobs_id_get

        Retrieve job  # noqa: E501
        """
        pass

    def test_read_jobs_jobs_get(self):
        """Test case for read_jobs_jobs_get

        List jobs  # noqa: E501
        """
        pass

    def test_start_job_jobs_id_start_patch(self):
        """Test case for start_job_jobs_id_start_patch

        Start job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
