# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.models.log_line import LogLine

class TestLogLine(unittest.TestCase):
    """LogLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogLine:
        """Test LogLine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogLine`
        """
        model = LogLine()
        if include_optional:
            return LogLine(
                timestamp = 56,
                line = ''
            )
        else:
            return LogLine(
                timestamp = 56,
                line = '',
        )
        """

    def testLogLine(self):
        """Test LogLine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
