# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.batch_jobs_api import BatchJobsApi


class TestBatchJobsApi(unittest.TestCase):
    """BatchJobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BatchJobsApi()

    def tearDown(self) -> None:
        pass

    def test_create_batch_job_batch_jobs_post(self) -> None:
        """Test case for create_batch_job_batch_jobs_post

        Create batch job
        """
        pass

    def test_enqueue_batch_job_batch_jobs_id_enqueue_patch(self) -> None:
        """Test case for enqueue_batch_job_batch_jobs_id_enqueue_patch

        Enqueue batch job for execution
        """
        pass

    def test_finish_batch_job_batch_jobs_id_finish_patch(self) -> None:
        """Test case for finish_batch_job_batch_jobs_id_finish_patch

        Finish batch job
        """
        pass

    def test_peek_batch_job_batch_jobs_peek_patch(self) -> None:
        """Test case for peek_batch_job_batch_jobs_peek_patch

        Peek batch job
        """
        pass

    def test_pop_batch_job_batch_jobs_pop_patch(self) -> None:
        """Test case for pop_batch_job_batch_jobs_pop_patch

        Take batch job
        """
        pass

    def test_read_batch_jobs_batch_jobs_get(self) -> None:
        """Test case for read_batch_jobs_batch_jobs_get

        List batch jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
