# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.compile_stage import CompileStage

class TestCompileStage(unittest.TestCase):
    """CompileStage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompileStage(self):
        """Test CompileStage"""
        # inst = CompileStage()

if __name__ == '__main__':
    unittest.main()
