# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.teams_api import TeamsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_team_teams_id_get(self):
        """Test case for read_team_teams_id_get

        Retrieve teams  # noqa: E501
        """
        pass

    def test_read_teams_teams_get(self):
        """Test case for read_teams_teams_get

        List teams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
