# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from compute_api_client.models.user_in import UserIn

class TestUserIn(unittest.TestCase):
    """UserIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserIn:
        """Test UserIn
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserIn`
        """
        model = UserIn()
        if include_optional:
            return UserIn(
                full_name = '',
                email = '',
                is_superuser = True,
                is_staff = True,
                is_active = True,
                is_confirmed = True
            )
        else:
            return UserIn(
                full_name = '',
                email = '',
        )
        """

    def testUserIn(self):
        """Test UserIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
