# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.algorithms_api import AlgorithmsApi


class TestAlgorithmsApi(unittest.TestCase):
    """AlgorithmsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlgorithmsApi()

    def tearDown(self) -> None:
        pass

    def test_create_algorithm_algorithms_post(self) -> None:
        """Test case for create_algorithm_algorithms_post

        Create algorithm
        """
        pass

    def test_delete_algorithm_algorithms_id_delete(self) -> None:
        """Test case for delete_algorithm_algorithms_id_delete

        Destroy algorithm
        """
        pass

    def test_read_algorithm_algorithms_id_get(self) -> None:
        """Test case for read_algorithm_algorithms_id_get

        Retrieve algorithm
        """
        pass

    def test_read_algorithms_algorithms_get(self) -> None:
        """Test case for read_algorithms_algorithms_get

        List algorithms
        """
        pass

    def test_update_algorithm_algorithms_id_put(self) -> None:
        """Test case for update_algorithm_algorithms_id_put

        Update algorithm
        """
        pass


if __name__ == '__main__':
    unittest.main()
