# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.commits_api import CommitsApi


class TestCommitsApi(unittest.TestCase):
    """CommitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommitsApi()

    def tearDown(self) -> None:
        pass

    def test_create_commit_commits_post(self) -> None:
        """Test case for create_commit_commits_post

        Create commit
        """
        pass

    def test_delete_commit_commits_id_delete(self) -> None:
        """Test case for delete_commit_commits_id_delete

        Destroy commit
        """
        pass

    def test_read_commit_commits_id_get(self) -> None:
        """Test case for read_commit_commits_id_get

        Get commit by ID
        """
        pass

    def test_read_commits_commits_get(self) -> None:
        """Test case for read_commits_commits_get

        List commits
        """
        pass


if __name__ == '__main__':
    unittest.main()
