# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_file_files_post(self) -> None:
        """Test case for create_file_files_post

        Create file
        """
        pass

    def test_delete_file_files_id_delete(self) -> None:
        """Test case for delete_file_files_id_delete

        Destroy file
        """
        pass

    def test_read_file_files_id_get(self) -> None:
        """Test case for read_file_files_id_get

        Retrieve file
        """
        pass

    def test_read_files_files_get(self) -> None:
        """Test case for read_files_files_get

        List files
        """
        pass


if __name__ == '__main__':
    unittest.main()
