# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.runtime_api import RuntimeApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestRuntimeApi(unittest.TestCase):
    """RuntimeApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.runtime_api.RuntimeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_runtime_runtimes_id_get(self):
        """Test case for read_runtime_runtimes_id_get

        Retrieve runtimes  # noqa: E501
        """
        pass

    def test_read_runtimes_runtimes_get(self):
        """Test case for read_runtimes_runtimes_get

        List runtimes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
