# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.reservations_api import ReservationsApi


class TestReservationsApi(unittest.TestCase):
    """ReservationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReservationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_reservation_reservations_post(self) -> None:
        """Test case for create_reservation_reservations_post

        Create reservation
        """
        pass

    def test_read_reservation_reservations_id_get(self) -> None:
        """Test case for read_reservation_reservations_id_get

        Retrieve reservation
        """
        pass

    def test_read_reservations_reservations_get(self) -> None:
        """Test case for read_reservations_reservations_get

        List reservations
        """
        pass

    def test_terminate_reservation_reservations_id_terminate_patch(self) -> None:
        """Test case for terminate_reservation_reservations_id_terminate_patch

        Terminate reservation
        """
        pass


if __name__ == '__main__':
    unittest.main()
