# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.languages_api import LanguagesApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestLanguagesApi(unittest.TestCase):
    """LanguagesApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.languages_api.LanguagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_language_languages_id_get(self):
        """Test case for read_language_languages_id_get

        Retrieve language  # noqa: E501
        """
        pass

    def test_read_languages_languages_get(self):
        """Test case for read_languages_languages_get

        List languages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
