# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.models.backend_with_hostname import BackendWithHostname

class TestBackendWithHostname(unittest.TestCase):
    """BackendWithHostname unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendWithHostname:
        """Test BackendWithHostname
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendWithHostname`
        """
        model = BackendWithHostname()
        if include_optional:
            return BackendWithHostname(
                id = 56,
                name = '',
                location = '',
                backend_type_id = 56,
                status = 'offline',
                message = compute_api_client.models.backend_message.BackendMessage(
                    content = '', ),
                last_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hostname = ''
            )
        else:
            return BackendWithHostname(
                id = 56,
                name = '',
                location = '',
                backend_type_id = 56,
                status = 'offline',
                last_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hostname = '',
        )
        """

    def testBackendWithHostname(self):
        """Test BackendWithHostname"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
