# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_create_project_projects_post(self) -> None:
        """Test case for create_project_projects_post

        Create project
        """
        pass

    def test_delete_project_projects_id_delete(self) -> None:
        """Test case for delete_project_projects_id_delete

        Destroy project
        """
        pass

    def test_partial_update_project_projects_id_patch(self) -> None:
        """Test case for partial_update_project_projects_id_patch

        Partially update project
        """
        pass

    def test_read_project_projects_id_get(self) -> None:
        """Test case for read_project_projects_id_get

        Retrieve project
        """
        pass

    def test_read_projects_projects_get(self) -> None:
        """Test case for read_projects_projects_get

        List projects
        """
        pass

    def test_update_project_projects_id_put(self) -> None:
        """Test case for update_project_projects_id_put

        Update project
        """
        pass


if __name__ == '__main__':
    unittest.main()
