# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.permissions_api import PermissionsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.permissions_api.PermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_permission_group_permission_groups_id_get(self):
        """Test case for read_permission_group_permission_groups_id_get

        Retrieve permission groups  # noqa: E501
        """
        pass

    def test_read_permission_groups_permission_groups_get(self):
        """Test case for read_permission_groups_permission_groups_get

        List permission groups  # noqa: E501
        """
        pass

    def test_read_permission_permissions_id_get(self):
        """Test case for read_permission_permissions_id_get

        Retrieve permissions  # noqa: E501
        """
        pass

    def test_read_permissions_permissions_get(self):
        """Test case for read_permissions_permissions_get

        List permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
