# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.models.drain_mode_in import DrainModeIn

class TestDrainModeIn(unittest.TestCase):
    """DrainModeIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DrainModeIn:
        """Test DrainModeIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DrainModeIn`
        """
        model = DrainModeIn()
        if include_optional:
            return DrainModeIn(
                enabled = True,
                reason = ''
            )
        else:
            return DrainModeIn(
                enabled = True,
                reason = '',
        )
        """

    def testDrainModeIn(self):
        """Test DrainModeIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
