# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import compute_api_client
from compute_api_client.models.batch_job import BatchJob  # noqa: E501
from compute_api_client.rest import ApiException

class TestBatchJob(unittest.TestCase):
    """BatchJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BatchJob
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = compute_api_client.models.batch_job.BatchJob()  # noqa: E501
        if include_optional :
            return BatchJob(
                id = 56, 
                created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                status = 'planned', 
                reserved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                user_id = 56, 
                backend_type_id = 56, 
                backend_id = 56, 
                queued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                job_ids = [
                    56
                    ], 
                aggregated_algorithm_type = 'hybrid'
            )
        else :
            return BatchJob(
                id = 56,
                created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'planned',
                user_id = 56,
                backend_type_id = 56,
                job_ids = [
                    56
                    ],
                aggregated_algorithm_type = 'hybrid',
        )

    def testBatchJob(self):
        """Test BatchJob"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
