# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import compute_api_client
from compute_api_client.models.runtime_type import RuntimeType  # noqa: E501
from compute_api_client.rest import ApiException

class TestRuntimeType(unittest.TestCase):
    """RuntimeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RuntimeType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = compute_api_client.models.runtime_type.RuntimeType()  # noqa: E501
        if include_optional :
            return RuntimeType(
                name = '', 
                infrastructure = '', 
                description = '', 
                image_id = '', 
                is_hardware = True, 
                required_permissions = [
                    ''
                    ], 
                features = [
                    ''
                    ], 
                default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(), 
                native_gateset = compute_api_client.models.native_gateset.Native Gateset(), 
                id = 56
            )
        else :
            return RuntimeType(
                name = '',
                infrastructure = '',
                description = '',
                image_id = '',
                is_hardware = True,
                required_permissions = [
                    ''
                    ],
                features = [
                    ''
                    ],
                default_compiler_config = compute_api_client.models.default_compiler_config.Default Compiler Config(),
                native_gateset = compute_api_client.models.native_gateset.Native Gateset(),
                id = 56,
        )

    def testRuntimeType(self):
        """Test RuntimeType"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
