# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.batch_runs_api import BatchRunsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestBatchRunsApi(unittest.TestCase):
    """BatchRunsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.batch_runs_api.BatchRunsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_batch_run_batch_runs_post(self):
        """Test case for create_batch_run_batch_runs_post

        Create batch run  # noqa: E501
        """
        pass

    def test_peek_batch_run_batch_runs_peek_patch(self):
        """Test case for peek_batch_run_batch_runs_peek_patch

        Peek batch run  # noqa: E501
        """
        pass

    def test_pop_batch_run_batch_runs_pop_patch(self):
        """Test case for pop_batch_run_batch_runs_pop_patch

        Take batch run  # noqa: E501
        """
        pass

    def test_read_batch_runs_batch_runs_get(self):
        """Test case for read_batch_runs_batch_runs_get

        List batch runs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
