# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataApi()

    def tearDown(self) -> None:
        pass

    def test_create_metadata_self_metadata_post(self) -> None:
        """Test case for create_metadata_self_metadata_post

        Create metadata
        """
        pass

    def test_read_metadata_by_backend_id_metadata_backend_backend_id_get(self) -> None:
        """Test case for read_metadata_by_backend_id_metadata_backend_backend_id_get

        Retrieve metadata by backend ID
        """
        pass

    def test_read_metadata_metadata_id_get(self) -> None:
        """Test case for read_metadata_metadata_id_get

        Get metadata by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
