# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.api.drain_mode_api import DrainModeApi


class TestDrainModeApi(unittest.IsolatedAsyncioTestCase):
    """DrainModeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DrainModeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_read_drain_mode_drain_mode_get(self) -> None:
        """Test case for read_drain_mode_drain_mode_get

        Retrieve drain mode statistics for all backendtypes
        """
        pass

    async def test_update_drain_mode_drain_mode_patch(self) -> None:
        """Test case for update_drain_mode_drain_mode_patch

        Enable drain mode for all backendtypes
        """
        pass


if __name__ == '__main__':
    unittest.main()
