# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.algorithms_api import AlgorithmsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestAlgorithmsApi(unittest.TestCase):
    """AlgorithmsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.algorithms_api.AlgorithmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_algorithm_algorithms_post(self):
        """Test case for create_algorithm_algorithms_post

        Create algorithm  # noqa: E501
        """
        pass

    def test_delete_algorithm_algorithms_id_delete(self):
        """Test case for delete_algorithm_algorithms_id_delete

        Destroy algorithm  # noqa: E501
        """
        pass

    def test_read_algorithm_algorithms_id_get(self):
        """Test case for read_algorithm_algorithms_id_get

        Retrieve algorithm  # noqa: E501
        """
        pass

    def test_read_algorithms_algorithms_get(self):
        """Test case for read_algorithms_algorithms_get

        List algorithms  # noqa: E501
        """
        pass

    def test_update_algorithm_algorithms_id_put(self):
        """Test case for update_algorithm_algorithms_id_put

        Update algorithm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
