# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.models.queue import Queue

class TestQueue(unittest.TestCase):
    """Queue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Queue:
        """Test Queue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Queue`
        """
        model = Queue()
        if include_optional:
            return Queue(
                number_of_jobs_in_queue = 56,
                min_wait_time_in_queue = 1.337,
                avg_wait_time_in_queue = 1.337,
                max_wait_time_in_queue = 1.337
            )
        else:
            return Queue(
                number_of_jobs_in_queue = 56,
                min_wait_time_in_queue = 1.337,
                avg_wait_time_in_queue = 1.337,
                max_wait_time_in_queue = 1.337,
        )
        """

    def testQueue(self):
        """Test Queue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
