# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import compute_api_client
from compute_api_client.models.algorithm import Algorithm  # noqa: E501
from compute_api_client.rest import ApiException

class TestAlgorithm(unittest.TestCase):
    """Algorithm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Algorithm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = compute_api_client.models.algorithm.Algorithm()  # noqa: E501
        if include_optional :
            return Algorithm(
                project_id = 56, 
                type = 'hybrid', 
                shared = 'private', 
                link = '', 
                id = 56
            )
        else :
            return Algorithm(
                project_id = 56,
                type = 'hybrid',
                shared = 'private',
                id = 56,
        )

    def testAlgorithm(self):
        """Test Algorithm"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
