# coding: utf-8

"""
    Quantum Inspire 2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compute_api_client.models.page_backend_with_hostname import PageBackendWithHostname

class TestPageBackendWithHostname(unittest.TestCase):
    """PageBackendWithHostname unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageBackendWithHostname:
        """Test PageBackendWithHostname
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageBackendWithHostname`
        """
        model = PageBackendWithHostname()
        if include_optional:
            return PageBackendWithHostname(
                items = [
                    compute_api_client.models.backend_with_hostname.BackendWithHostname(
                        id = 56, 
                        name = '', 
                        location = '', 
                        backend_type_id = 56, 
                        status = 'offline', 
                        message = compute_api_client.models.backend_message.BackendMessage(
                            content = '', ), 
                        last_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hostname = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageBackendWithHostname(
                items = [
                    compute_api_client.models.backend_with_hostname.BackendWithHostname(
                        id = 56, 
                        name = '', 
                        location = '', 
                        backend_type_id = 56, 
                        status = 'offline', 
                        message = compute_api_client.models.backend_message.BackendMessage(
                            content = '', ), 
                        last_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hostname = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0,
        )
        """

    def testPageBackendWithHostname(self):
        """Test PageBackendWithHostname"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
