# coding: utf-8

"""
    Compute Job Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import compute_api_client
from compute_api_client.api.transactions_api import TransactionsApi  # noqa: E501
from compute_api_client.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = compute_api_client.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_transaction_transactions_id_get(self):
        """Test case for read_transaction_transactions_id_get

        Retrieve transactions  # noqa: E501
        """
        pass

    def test_read_transactions_transactions_get(self):
        """Test case for read_transactions_transactions_get

        List transactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
